"""
Setup Wizard - Guides the user through initial configuration
Handles wallet setup, RPC connection, and .env generation
"""

import os
import sys
import time
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich.progress import Progress, SpinnerColumn, TextColumn
from eth_account import Account
from web3 import Web3
import re

console = Console()

class SetupWizard:
    def __init__(self):
        self.env_path = ".env"
        self.config = {}
        
    def run(self):
        """Main setup loop"""
        console.clear()
        console.print(Panel.fit(
            "[bold blue]WELCOME TO POLYMARKET BOT SETUP[/bold blue]\n"
            "I'll help you configure your bot to start trading safely.",
            border_style="blue"
        ))
        
        console.print("\n[yellow]Step 1: Polygon Wallet Configuration[/yellow]")
        console.print("You need a Polygon wallet private key (e.g., from MetaMask).")
        console.print("This key is stored [bold red]ONLY LOCALLY[/bold red] in your .env file.")
        
        while True:
            private_key = Prompt.ask("[cyan]Enter your Polygon Private Key (starts with 0x)[/cyan]", password=True)
            if not private_key.startswith("0x"):
                private_key = "0x" + private_key
                
            if self._validate_private_key(private_key):
                self.config['WALLET_PRIVATE_KEY'] = private_key
                break
            else:
                console.print("[red]Invalid private key format. Please ensure it's a 64-character hex string.[/red]")

        console.print("\n[yellow]Step 2: RPC Connection[/yellow]")
        rpc_url = Prompt.ask(
            "[cyan]Enter Polygon RPC URL[/cyan]", 
            default="https://polygon-rpc.com"
        )
        
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            transient=True,
        ) as progress:
            progress.add_task(description="Testing connection...", total=None)
            if self._test_rpc(rpc_url):
                self.config['POLYGON_RPC_URL'] = rpc_url
                console.print("[green]Connected to Polygon successfully![/green]")
            else:
                console.print("[yellow]Could not connect to this RPC. Using default fallback.[/yellow]")
                self.config['POLYGON_RPC_URL'] = "https://polygon-rpc.com"

        console.print("\n[yellow]Step 3: Polymarket Funder/Proxy Address[/yellow]")
        console.print("If you use a Proxy Wallet (Gnosis Safe) on Polymarket, enter it below.")
        console.print("Find this in [bold]polymarket.com > Settings[/bold].")
        funder = Prompt.ask("[cyan]Enter Proxy/Funder Address (Optional, press Enter to skip)[/cyan]")
        if funder and self._validate_address(funder):
            self.config['PROXY_ADDRESS'] = funder
        else:
            self.config['PROXY_ADDRESS'] = ""

        self._save_env()
        
        console.print(Panel.fit(
            "[bold green]CONFIGURATION SAVED![/bold green]\n"
            "Your .env file has been updated. The bot will now verify your balance.",
            border_style="green"
        ))
        time.sleep(2)
        return True

    def _validate_private_key(self, key: str) -> bool:
        try:
            if len(key) != 66: return False # 0x + 64 hex
            Account.from_key(key)
            return True
        except:
            return False

    def _validate_address(self, address: str) -> bool:
        return Web3.is_address(address)

    def _test_rpc(self, url: str) -> bool:
        try:
            w3 = Web3(Web3.HTTPProvider(url))
            return w3.is_connected()
        except:
            return False

    def _save_env(self):
        """Updates or creates .env file while preserving other values"""
        existing_env = {}
        if os.path.exists(self.env_path):
            with open(self.env_path, 'r') as f:
                for line in f:
                    if "=" in line and not line.startswith("#"):
                        key, val = line.strip().split("=", 1)
                        existing_env[key] = val
        
        # Merge new config
        existing_env.update(self.config)
        
        with open(self.env_path, 'w') as f:
            f.write("# =============================================================================\n")
            f.write("# Polymarket Bot Configuration - Generated by Setup Wizard\n")
            f.write("# =============================================================================\n")
            for key, val in existing_env.items():
                f.write(f"{key}={val}\n")

def check_setup_required():
    """Checks if critical data is missing or is a placeholder"""
    pk = os.getenv('WALLET_PRIVATE_KEY')
    if not pk or "YOUR_PRIVATE_KEY" in pk or len(pk) < 64:
        return True
    return False

if __name__ == "__main__":
    wizard = SetupWizard()
    wizard.run()
